repository: john20xdoe/john20xdoe.gihub.io
github: [metadata]
theme: jekyll-theme-leap-day
google_analytics: UA-103613736-1
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" 
  -
    scope:
      path: "til"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "til"
  -
    scope:
      path: "skills"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "skills"